# Generated by Django 5.2 on 2025-04-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_students_created_at_students_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
