# Generated by Django 5.2 on 2025-04-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_students_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='mobile',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
