# Generated by Django 5.2 on 2025-04-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='mlyfee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
