# Generated by Django 5.2 on 2025-05-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_students_gender_students_mlyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='yrlyfee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
