# Generated by Django 5.2 on 2025-05-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_students_yrlyfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='yrlyfee',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
